openapi: "3.0.0"
info:
  version: "2019-07-22"
  title: Article Endpoint Demo Docs

servers:
  - url: http://localhost:{port}/api
    description: Local server
    variables:
      port:
        enum:
          - '8087'
        default: '8087'

paths:
  /articles:
    get:
      operationId: get
      summary: Gets some articles
      tags:
        - Article
      responses:
        200:
          description: Successfully returns Articles
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Article'

components:
  schemas:
    Article:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier
        name:
          type: string
          description: The name of the article
        supplier:
          type: string
        type:
          type: string
          enum: [clothes, books, media]